<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_bot">

  <!-- ================= GLOBAL ================= -->
  <xacro:property name="base_length" value="0.55"/>
  <xacro:property name="base_width"  value="0.40"/>
  <xacro:property name="base_height" value="0.18"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width"  value="0.05"/>
  <xacro:property name="wheel_sep"    value="0.36"/>

  <xacro:property name="robot_mass" value="22.0"/>

  <!-- ================= INERTIA MACRO ================= -->
  <xacro:macro name="inertial_box" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <origin xyz="0 0 0"/>
      <inertia
        ixx="${m*(y*y+z*z)/12}"
        iyy="${m*(x*x+z*z)/12}"
        izz="${m*(x*x+y*y)/12}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- ================= BASE ================= -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box m="${robot_mass}"
                        x="${base_length}"
                        y="${base_width}"
                        z="${base_height}"/>
  </link>

  <!-- ================= WHEELS ================= -->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 ${wheel_sep/2} ${wheel_radius}" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${wheel_sep/2} ${wheel_radius}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_box m="2.0"
                        x="${wheel_width}"
                        y="${wheel_radius*2}"
                        z="${wheel_radius*2}"/>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_sep/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <origin xyz="0 ${-wheel_sep/2} ${wheel_radius}" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${-wheel_sep/2} ${wheel_radius}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_box m="2.0"
                        x="${wheel_width}"
                        y="${wheel_radius*2}"
                        z="${wheel_radius*2}"/>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-wheel_sep/2} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ================= FIXED FLAPS (GUIDES) ================= -->

  <link name="left_flap">
    <visual>
      <origin xyz="0.30 0.30 0.20" rpy="0 0 -0.5"/>
      <geometry>
        <box size="0.60 0.05 0.35"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.30 0.30 0.20" rpy="0 0 -0.5"/>
      <geometry>
        <box size="0.60 0.05 0.35"/>
      </geometry>
    </collision>
    <xacro:inertial_box m="4.0" x="0.6" y="0.05" z="0.35"/>
  </link>

  <joint name="left_flap_joint" type="fixed">
    <parent link="base_link"/>
    <child link="left_flap"/>
    <origin xyz="0 0 0"/>
  </joint>

  <link name="right_flap">
    <visual>
      <origin xyz="0.30 -0.30 0.20" rpy="0 0 0.5"/>
      <geometry>
        <box size="0.60 0.05 0.35"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.30 -0.30 0.20" rpy="0 0 0.5"/>
      <geometry>
        <box size="0.60 0.05 0.35"/>
      </geometry>
    </collision>
    <xacro:inertial_box m="4.0" x="0.6" y="0.05" z="0.35"/>
  </link>

  <joint name="right_flap_joint" type="fixed">
    <parent link="base_link"/>
    <child link="right_flap"/>
    <origin xyz="0 0 0"/>
  </joint>

  <!-- ================= LIDAR SENSOR ================= -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0.10 0 ${base_height + 0.15}"/>
      <geometry>
        <cylinder radius="0.06" length="0.08"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.10 0 ${base_height + 0.15}"/>
      <geometry>
        <cylinder radius="0.06" length="0.08"/>
      </geometry>
    </collision>
    <xacro:inertial_box m="0.3" x="0.08" y="0.08" z="0.08"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0"/>
  </joint>

  <!-- ================= DIFF DRIVE ================= -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_sep}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
  </gazebo>

</robot>
